<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./style.css" type="text/css"?>
<!DOCTYPE student [
    <!ELEMENT student (h1, student-info+)>
    <!ELEMENT student-info (h2, ad+)>
    <!ELEMENT ad (label)>
    <!ELEMENT usn (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT col (#PCDATA)>
    <!ELEMENT branch (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT label (#PCDATA|usn|name|branch|col|year|email)*>
    <!ELEMENT h2 (#PCDATA)>
    <!ELEMENT h1 (#PCDATA)>
]>
<student>
    <h1>Student information</h1>
    <student-info>
        <h2>Student 1</h2>
        <ad><label>USN:<usn>4SN17CS096</usn></label></ad>
        <ad><label>Name:<name>Sohan DSa</name></label></ad>
        <ad><label>Branch:<branch>CS</branch></label></ad>
        <ad><label>College:<col>SIT</col></label></ad>
        <ad><label>Year:<year>2017</year></label></ad>
        <ad><label>Email:<email>abs@email.com</email></label></ad>
    </student-info>
    <student-info>
        <h2>Student 2</h2>
        <ad><label>USN:<usn>4SN17CS096</usn></label></ad>
        <ad><label>Name:<name>Sohan DSa</name></label></ad>
        <ad><label>Branch:<branch>CS</branch></label></ad>
        <ad><label>College:<col>SIT</col></label></ad>
        <ad><label>Year:<year>2017</year></label></ad>
        <ad><label>Email:<email>abs@email.com</email></label></ad>
    </student-info>
    <student-info>
        <h2>Student 3</h2>
        <ad><label>USN:<usn>4SN17CS096</usn></label></ad>
        <ad><label>Name:<name>Sohan DSa</name></label></ad>
        <ad><label>Branch:<branch>CS</branch></label></ad>
        <ad><label>College:<col>SIT</col></label></ad>
        <ad><label>Year:<year>2017</year></label></ad>
        <ad><label>Email:<email>abs@email.com</email></label></ad>
    </student-info>
</student>